services:
  - type: web
    name: mixtli-backend-compat
    env: node
    region: oregon
    plan: starter
    branch: main
    autoDeploy: true
    buildCommand: |
      npm ci --no-audit --no-fund || npm install --no-audit --no-fund
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: PORT
        value: "10000"
      - key: ALLOWED_ORIGINS
        value: '["https://unrivaled-churros-366919.netlify.app","http://localhost:5173"]'
      - key: REQUIRE_TOKEN
        value: "false"
      - key: X_MIXTLI_TOKEN
        fromSecret: mixtli-token-privado